name: Terraform Plan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

  pull_request:
    branches:
      - main
      - staging
      - dev

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    env:
      TF_VERSION: "1.12.2"

      # Terraform automatically picks these up
      TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # Optional - remove after confirming AWS authentication works
      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Select Environment
        id: environment
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "name=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          else
            echo "name=dev" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Init
        working-directory: environments/${{ steps.environment.outputs.name }}
        run: |
          terraform init \
            -backend-config=backend-${{ steps.environment.outputs.name }}.hcl

      - name: Terraform Validate
        working-directory: environments/${{ steps.environment.outputs.name }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: environments/${{ steps.environment.outputs.name }}
        run: terraform plan -no-color
